# Example Kaggle Notebook
## This is Great

In [66]:
import numpy as np

In [67]:
a = np.array([i for i in range(0, 9)])
print(f"{a=}")

a=array([0, 1, 2, 3, 4, 5, 6, 7, 8])


print("test test 123")

In [68]:
# Розминка

In [69]:
np.sqrt(4)

2.0

In [70]:
a = [3, 5, 6, 4]
b = [2, 5, 7, 7]

In [71]:
a= np.array(a)
b= np.array(b)

In [72]:
type(a)

numpy.ndarray

In [73]:
a.size

4

In [74]:
a+4

array([ 7,  9, 10,  8])

In [75]:
a - 2

array([1, 3, 4, 2])

In [76]:
a

array([3, 5, 6, 4])

In [77]:
b

array([2, 5, 7, 7])

In [78]:
3*a + 5*b

array([19, 40, 53, 47])

#### добуток

In [79]:
print(a)
print(b)
print(a*b)

[3 5 6 4]
[2 5 7 7]
[ 6 25 42 28]


In [80]:
c = a*b
print(c)
print(b)
print(c/b)

[ 6 25 42 28]
[2 5 7 7]
[3. 5. 6. 4.]


In [81]:
print(type(c[0]))
print(type((c/b)[0]))

<class 'numpy.int64'>
<class 'numpy.float64'>


#### скалярний добуток

In [82]:
np.dot(a,b)

101

In [83]:
(a*b).sum()

101

## Matrix

In [84]:
matrix = np.array(
    [
        [2, 4, 6, 7, 6],
        [3, 6, 6, 7, 6],
        [1, 3, 2, 4, 79],
        [7, 4, 6, 54, 6],
    ]
)

In [85]:
print(matrix[0][0])
print(matrix[2][4])
print(matrix[3, 3])

2
79
54


In [86]:
matrix[:2]

array([[2, 4, 6, 7, 6],
       [3, 6, 6, 7, 6]])

In [87]:
matrix[:2, 3:]

array([[7, 6],
       [7, 6]])

In [88]:
matrix[2:, 3:]

array([[ 4, 79],
       [54,  6]])

In [89]:
ones = np.ones((4, 3))
zeros = np.zeros(ones.shape)
print(ones)
print(zeros)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [90]:
zeros*ones

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [91]:
# np.dot(ones, zeros) ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [92]:
np.dot(ones, zeros.T)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [93]:
matrix.shape

(4, 5)

In [96]:
print(ones.shape)
ones = ones.T
ones.shape

(3, 4)


(4, 3)

In [95]:
np.dot(ones, matrix)

array([[13., 17., 20., 72., 97.],
       [13., 17., 20., 72., 97.],
       [13., 17., 20., 72., 97.]])

In [109]:
print(f"{matrix[:, :]=}")
print(f"{matrix[1:, 0]=}")
print(f"{ones=}")
print(f"{ones[0]=}")
print(f"{np.dot(ones[0], matrix[1:, 0])=}")

matrix[:, :]=array([[ 2,  4,  6,  7,  6],
       [ 3,  6,  6,  7,  6],
       [ 1,  3,  2,  4, 79],
       [ 7,  4,  6, 54,  6]])
matrix[1:, 0:]=array([[ 3,  6,  6,  7,  6],
       [ 1,  3,  2,  4, 79],
       [ 7,  4,  6, 54,  6]])
ones=array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])
ones[0]=array([1., 1., 1.])
np.dot(ones[0], matrix[1:, 0])=11.0


In [110]:
matrix

array([[ 2,  4,  6,  7,  6],
       [ 3,  6,  6,  7,  6],
       [ 1,  3,  2,  4, 79],
       [ 7,  4,  6, 54,  6]])

In [112]:
matrix.size

20

In [111]:
matrix.reshape(2, 10)

array([[ 2,  4,  6,  7,  6,  3,  6,  6,  7,  6],
       [ 1,  3,  2,  4, 79,  7,  4,  6, 54,  6]])

### Обернена матриця = Invertible matrix

In [119]:
I = np.identity(5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [118]:
matrix = matrix.reshape((5,4))
matrix

array([[ 2,  4,  6,  7],
       [ 6,  3,  6,  6],
       [ 7,  6,  1,  3],
       [ 2,  4, 79,  7],
       [ 4,  6, 54,  6]])

In [121]:
np.dot(I, matrix)

array([[ 2.,  4.,  6.,  7.],
       [ 6.,  3.,  6.,  6.],
       [ 7.,  6.,  1.,  3.],
       [ 2.,  4., 79.,  7.],
       [ 4.,  6., 54.,  6.]])

In [122]:
np.dot(I, matrix) == matrix

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [123]:
E = np.eye(5, k=-1)
E

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [124]:
(matrix.T).T

array([[ 2,  4,  6,  7],
       [ 6,  3,  6,  6],
       [ 7,  6,  1,  3],
       [ 2,  4, 79,  7],
       [ 4,  6, 54,  6]])

In [125]:
(matrix.T).T == matrix

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [126]:
matrix1 = np.linalg.pinv(matrix)
matrix1

array([[-0.17455686,  0.1922031 ,  0.04416523,  0.02651899, -0.04157487],
       [ 0.134457  , -0.25770842,  0.13446446, -0.07561745,  0.12183005],
       [-0.01433291,  0.00105233, -0.00210465,  0.01117593,  0.00368314],
       [ 0.12596161,  0.0951308 , -0.0950235 ,  0.01721743, -0.04799459]])

In [127]:
matrix1.shape

(4, 5)

In [130]:
np.dot(matrix1, matrix)

array([[ 1.00000000e+00,  5.41233725e-16, -2.48412402e-15,
         1.38777878e-17],
       [-1.11022302e-16,  1.00000000e+00,  1.77635684e-15,
         2.22044605e-16],
       [-8.84708973e-17, -2.51534904e-17,  1.00000000e+00,
        -7.80625564e-18],
       [ 1.38777878e-16, -6.93889390e-17, -6.93889390e-17,
         1.00000000e+00]])

In [131]:
matrix.sum()

219

In [132]:
matrix.min()

1

In [133]:
matrix.max()

79

In [134]:
matrix.mean()

10.95

In [135]:
print(np.sum(matrix))
print(np.mean(matrix))

219
10.95


In [136]:
np.prod(matrix)

943748335337472

In [138]:
matrix

array([[ 2,  4,  6,  7],
       [ 6,  3,  6,  6],
       [ 7,  6,  1,  3],
       [ 2,  4, 79,  7],
       [ 4,  6, 54,  6]])

In [140]:
np.power(np.sqrt(matrix), 2)

array([[ 2.,  4.,  6.,  7.],
       [ 6.,  3.,  6.,  6.],
       [ 7.,  6.,  1.,  3.],
       [ 2.,  4., 79.,  7.],
       [ 4.,  6., 54.,  6.]])

In [142]:
np.log(matrix)

array([[0.69314718, 1.38629436, 1.79175947, 1.94591015],
       [1.79175947, 1.09861229, 1.79175947, 1.79175947],
       [1.94591015, 1.79175947, 0.        , 1.09861229],
       [0.69314718, 1.38629436, 4.36944785, 1.94591015],
       [1.38629436, 1.79175947, 3.98898405, 1.79175947]])