In [ ]:
#Встaновити numpy
#!pip install numpy

In [ ]:
# Приклади роботи з матрицями
import numpy as np
# Отримання версії бібліотеки NumPy
numpy_version = np.__version__
numpy_version


'2.0.2'

In [ ]:
#1. Задати вектор
v = np.array([1, 2, 3, 4, 5], dtype = float)
v

array([1., 2., 3., 4., 5.])

In [ ]:
v[0]

np.float64(1.0)

In [ ]:
v[-1]


np.float64(5.0)

In [ ]:
#2. Задати масив (матрицю) 2*3
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#3. Вивести елемент a22
a[1,1]

np.int64(5)

In [ ]:
#4. Вивести елемент a11
a[0,0]

np.int64(1)

In [ ]:
#5. Вивести тип елементів
a.dtype

dtype('int64')

In [ ]:
a.size

6

In [ ]:
a.shape

(2, 3)

In [ ]:

# 6. Задаємо матрицю 3*3
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#7 Ще один варіант задати матрицю
b = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# 8.  Побудуємо діагональ
diag = np.diag(a)
diag

array([1, 5, 9])

In [ ]:
# 9. Побудуємо діагональну матрицю на основі діагоналі
a_diag = np.diag(diag)

a_diag

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [ ]:
#10. Масив, вектор, заповнений нулями
np.zeros(2)

array([0., 0.])

In [ ]:
# 11. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
np.zeros((3, 3), dtype=int)


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
# 12. Створіть масив розміром 4x4, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
np.random.randint(11, size=(4,4))


array([[ 1,  4,  0,  3],
       [ 0,  6, 10,  2],
       [ 4,  8,  9,  7],
       [ 3,  1,  0,  4]])

In [ ]:
#13.  Масив (вектор) заповнений одиницями
np.ones(2)

array([1., 1.])

In [ ]:
# 14. Масив чисел від 2 до 9 з кроком 2
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [ ]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
#15. матриця з одиниць розмір 3*3
matrix = np.ones((3, 3), dtype=int)
matrix

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
# 16. Транспонувати матрицю
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
 a.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
# 17. Визначник матриці
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [ ]:
a_det = np.linalg.det(a)
a_det

np.float64(-2.0000000000000004)

In [ ]:
# 18. Множення матриці на число
a = np.matrix([[1, 2, 3], [4, 5, 6]])
c = 3 * a
c

matrix([[ 3,  6,  9],
        [12, 15, 18]])

In [ ]:
# 19. Додавання матриць
a = np.matrix([[1, 6, 3], [8, 2, 7]])
b = np.matrix([[8, 1, 5], [6, 9, 12]])
c = a + b
c

matrix([[ 9,  7,  8],
        [14, 11, 19]])

In [ ]:
# 20. Добуток матриць
a = np.matrix([[1, 2], [4, 5]])
b = np.matrix([[7, 8], [9, 1]])
c = np.dot(a, b)
c

matrix([[25, 10],
        [73, 37]])

In [ ]:
# 21 Обернена матриця
a = np.matrix([[1, -3], [2, 5]])
a_inv = np.linalg.inv(a)
a_inv

matrix([[ 0.45454545,  0.27272727],
        [-0.18181818,  0.09090909]])

In [ ]:
# 22. Ранг матриці
rank = np.linalg.matrix_rank(a)
rank

np.int64(2)

In [ ]:
a = np.array([[1, 6, 3], [8, 2, 7]])
b = np.array([[8, 1, 5], [6, 9, 12]])

c1 = a*b
print("Поелементний добуток матриць:")
print(c1)

Поелементний добуток матриць:
[[ 8  6 15]
 [48 18 84]]


In [ ]:
#23 Розв*язання систем лінійних рівнянь.

import numpy as np

# Матричний метод
def matrix_method(coefficients, constants):
    inverse_matrix = np.linalg.inv(coefficients)
    return np.dot(inverse_matrix, constants)

# Метод Крамера
def cramer_method(coefficients, constants):
    det_coefficients = np.linalg.det(coefficients)
    solutions = []
    for i in range(len(coefficients)):
        modified_coefficients = np.copy(coefficients)
        modified_coefficients[:, i] = constants
        solutions.append(round(np.linalg.det(modified_coefficients) / det_coefficients, 1))  # Округлюємо до десятих
    return solutions

#Метод Гауса

def gauss_method(a, b):
    n = len(b)

    for k in range(0, n-1):
        for i in range(k+1, n):
            if a[i, k] != 0.0:
                lam = a[i, k] / a[k, k]
                a[i, k+1:n] = a[i, k+1:n] - lam * a[k, k+1:n]
                b[i] = b[i] - lam * b[k]

    x = np.zeros(n)
    for k in range(n-1, -1, -1):
        x[k] = (b[k] - np.dot(a[k, k+1:n], x[k+1:n])) / a[k, k]

    return x

def main():
    # Приклад матриці A и вектора B для розв*язку системи рівнянь Ax = B
    a = np.array([[1.0, 1.0, 1.0],
                  [1.0, -1.0, -1.0],
                  [1.0, -2.0, 3.0]])

    b = np.array([1.0, 1.0, -5.0])

    # Матричний метод
    x_matrix = matrix_method(a, b)
    print("Матричний метод:", x_matrix)

    # Метод Крамера
    x_cramer = cramer_method(a, b)
    print("Метод Крамера:", x_cramer)

    # Метод Гауса
    x_gauss = gauss_method(a, b)
    print("Метод Гауса:", x_gauss)


if __name__ == "__main__":
    main()


Матричний метод: [ 1.   1.2 -1.2]
Метод Крамера: [np.float64(1.0), np.float64(1.2), np.float64(-1.2)]
Метод Гауса: [ 1.   1.2 -1.2]


In [ ]:
#Приклад 2 Розв*язання систем

import numpy as np

# Система рівнянь
a = np.array([[1, 1, 1], [0, 1, -1], [1, 0, -1]])
b = np.array([1500, 140, 80])

# Метод Крамера
def kramer(a, b):
    det_a = np.linalg.det(a)
    if det_a != 0:
        solutions = []
        for i in range(len(a)):
            modified_a = np.copy(a)
            modified_a[:, i] = b
            solutions.append(round(np.linalg.det(modified_a) / det_a, 1))

        print('Solving a system of linear algebraic equations by Cramer\'s method:')
        print('x =', solutions)

    else:
        print('Determinant equals zero, the system has no solutions')
    return solutions

# Метод Гауса
def gaussian_elimination(a, b):
    n = len(b)
    x = np.zeros(n)

    # Прямий хід
    for k in range(n-1):
        for i in range(k+1, n):
            factor = a[i,k] / a[k,k]
            for j in range(k, n):
                a[i,j] -= factor * a[k,j]
            b[i] -= factor * b[k]

    # Обернений хід
    x[n-1] = b[n-1] / a[n-1, n-1]
    for i in range(n-2, -1, -1):
        x[i] = (b[i] - np.dot(a[i,i+1:], x[i+1:])) / a[i,i]

    print('Solving a system of linear algebraic equations by Gaussian elimination method:')
    print('x =', x.round(1))

# Матричний метод
def matrix_method(a, b):
    x = np.linalg.inv(a).dot(b)
    print('Solving a system of linear algebraic equations by matrix method:')
    print('x =', x.round(1))

# Виклик функцій для розв'язання системи
kramer(a, b)
gaussian_elimination(a, b)
matrix_method(a, b)


Solving a system of linear algebraic equations by Cramer's method:
x = [np.float64(506.7), np.float64(566.7), np.float64(426.7)]
Solving a system of linear algebraic equations by Gaussian elimination method:
x = [506.7 566.7 426.7]
Solving a system of linear algebraic equations by matrix method:
x = [506.7 566.7 426.7]


In [ ]:
x = np.linalg.solve(a, b)
print('Перевірка:')
print('x =', x.round(1))

Перевірка:
x = [506.7 566.7 426.7]


In [ ]:
import numpy as np

A = np.array([[0, -2, 2],
              [-4,  0, 2],
              [0, 2, 0]])


eigenvalues, eigenvectors = np.linalg.eig(A)


print("Власні числа:")
print(eigenvalues)
print("\nВласні вектори:")
print(eigenvectors)

Власні числа:
[-4.          1.99999997  2.00000003]

Власні вектори:
[[-5.57086015e-01  1.11219577e-08 -1.11219579e-08]
 [-7.42781353e-01  7.07106776e-01  7.07106787e-01]
 [ 3.71390676e-01  7.07106787e-01  7.07106776e-01]]
