# Numpy


In [ ]:
#!pip install numpy

In [ ]:
import numpy as np

## Масиви та матриці
`ndarray`
`dtype`

In [ ]:
a = np.array([1, 2, 3, 4, 5], dtype=float)
a

array([1., 2., 3., 4., 5.])

In [ ]:
b = np.array([
              [1, 2, 3],
              [4, 5, 6]
              ],
    dtype=int)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.shape

(5,)

In [ ]:
b.shape

(2, 3)

In [ ]:
b.ndim

2

In [ ]:
a.size

5

In [ ]:
a.data

In [ ]:
b.itemsize

8

`shape` - виміри масиву

`ndim` - кількість осей (`ndim == len(shape)`)

`size` - загальна кількісь елем.

`dtype` - тип даних масиву

`data` - буфер в пам'яті, де знаходяться елементи масиву

`itemsize` - розмір у байтах кожного елем.

In [ ]:
np.ones((5,), dtype=float)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((2, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
np.zeros((5,), dtype=float)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2, 4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
np.identity(4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
a = np.arange(5)
b = np.arange(1, 3, 0.5)
print(a)
print(b)

[0 1 2 3 4]
[1.  1.5 2.  2.5]


In [ ]:
a = np.linspace(1, 5, num=5)
b = np.linspace(1, 3, num=3)
print(a)
print(b)

[1. 2. 3. 4. 5.]
[1. 2. 3.]


In [ ]:
a = np.random.random(3)
b = np.random.random((3, 3))
print(a)
print()
print(b)

[0.93153089 0.69852505 0.07013856]

[[0.94202308 0.06764488 0.07153966]
 [0.619995   0.05384441 0.70386433]
 [0.069732   0.45480726 0.41030504]]


## Індексація


In [ ]:
a = np.array([1, 2, 3, 4, 5])
print(a[0])
print(a[1:])
print(a[:2])

1
[2 3 4 5]
[1 2]


`m[i][j]` -> `m[i, j]`

In [ ]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(a[1, 1])
print(a[1:, 1])
print(a[0, :2])

5
[5 8]
[1 2]


## `dtype`


In [ ]:
np.uint16
np.int_
np.bool_

numpy.bool

`int_` - long C

`int8` - 1 byte [-128, 127]

`int16` - 2 byte [-32768, 32767]

`int32` - 4 byte [-2^31, 2^31 - 1]

`int64` - 8 byte [-2^63, 2^63 - 1]

`uint8` - 1 byte [0, 255]

`uint16` - 2 byte [0, 65535]

`uint32` - 4 byte [0, 2^32 - 1]

`uint64` - 8 byte [0, 2^64 - 1]

`float_` - float64

`float32` - [10^-38, 10^38] 7 знаків після коми

`float64` - [10^-308, 10^308] 15 знаків після коми

`complex_` - complex128

`complex64`, `complex128`

`bool_` - логічний тип даних, 1 байт

In [ ]:
b = np.zeros((3, 3), dtype="u4")
# i - int
# u - uint
# f - float
# c - complex
# b - bool
# S, a - str
# U - unicode symbols
b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint32)

In [ ]:
a = np.array([u"\u2211", u"\u220F"], dtype="U")
a

array(['∑', '∏'], dtype='<U1')

## Арифметичні операції

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.uint8)
b = np.array([[2, 2, 2], [3, 3, 3], [4, 4, 4]], dtype=np.uint8)

print(a.dtype)
print(b.dtype)
print(a + b)
print(a - b)
print(a * b)
print(a / b)

uint8
uint8
[[ 3  4  5]
 [ 7  8  9]
 [11 12 13]]
[[255   0   1]
 [  1   2   3]
 [  3   4   5]]
[[ 2  4  6]
 [12 15 18]
 [28 32 36]]
[[0.5        1.         1.5       ]
 [1.33333333 1.66666667 2.        ]
 [1.75       2.         2.25      ]]


## Агрегування даних

In [ ]:
a = np.array([1, 2, 3, 4, 5])
print(a.min())
print(a.max())
print(a.sum())
print(a.mean())
print(a.prod())

1
5
15
3.0
120


In [ ]:
a = np.array([[1, 2, 3], [100, 5, 6], [7, 8, 9]])
print(a.min())
print(a.max())
print(a.sum())
print(a.mean())
print(np.median(a))
print(a.prod())

1
100
141
15.666666666666666
6.0
9072000


## Лінійна алгебра

In [ ]:
a = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
diag = np.diag(a)
diag

array([1, 5, 9])

In [ ]:
b = np.diag(diag)
b

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [ ]:
np.eye(4, k=-1, dtype=int)

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

## Транспонування та зміна форми

In [ ]:
a = np.matrix('1,2,3;4,5,6;7,8,9')
b = a.T
b

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [ ]:
a = np.matrix('1,2,3;4,5,6')
b = a.reshape((3, 2))
b

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
a = np.matrix('1,2,3;4,5,6;7,8,9')
b = a.flatten()
b

matrix([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

## Множення матриць

In [ ]:
a = np.matrix('1,2,3;0,1,2')
b = np.matrix('1,2;0,4;-1,0')

c = a.dot(b)
c

matrix([[-2, 10],
        [-2,  4]])

## Визначник

In [ ]:
a = np.matrix('1,2,3;0,1,2;4,7,2')
det = round(np.linalg.det(a))
det

-8

 Обернена матриця

In [ ]:
a = np.matrix('1,2,3;0,1,2;4,7,2')
b = np.linalg.inv(a)

a.dot(b)

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

## Розв'язання лінійних алгебраїчних рівнянь

In [ ]:
a = np.matrix('1,2,5;1,-1,3;3,-6,-1')
b = np.matrix('-9;2;25')
a_inv = np.linalg.inv(a)
x = a_inv.dot(b)
x

matrix([[ 2.],
        [-3.],
        [-1.]])

In [ ]:
x = np.linalg.solve(a, b)
x

matrix([[ 2.],
        [-3.],
        [-1.]])