<a href="https://colab.research.google.com/github/SiracencoSerghei/DataScienceHW/blob/main/example_kaggle/les_1/conspect_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Для ілюстрації проведемо базовий EDA на прикладі датасету з бібліотеки seaborn.

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Завантаження датасету

df = sns.load_dataset('iris')

# Перегляд перших рядків даних

print(df.head())

# Основні статистичні характеристики

print(df.describe())

# Перевірка на пропущені значення

print('пропущені значення: ', df.isnull().sum())

# Візуалізація розподілу змінної

sns.histplot(df['sepal_length'], kde=True)
plt.show()

# Візуалізація взаємозв'язку між змінними

sns.pairplot(df, hue='species')
plt.show()


# Бібліотеки для автоматизації EDA

## 1. Pandas Profiling

In [ ]:
!pip install -U ydata-profiling

In [ ]:
from ydata_profiling import ProfileReport
profile = ProfileReport(df, title="Report")
profile


## 2. SweetViz

## 3. dabl (Experimental by scikit-learn team)

In [ ]:
!pip install dabl

In [ ]:
import dabl
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris(as_frame=True)
df = iris.frame

dabl.plot(df, target_col='target')

# Вектори

## Додавання/віднімання скаляра та вектора

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5], dtype=float)
print(a + 2)  # [3. 4. 5. 6. 7.]
print(a - 1)  # [0. 1. 2. 3. 4.]

[3. 4. 5. 6. 7.]
[0. 1. 2. 3. 4.]


## Множення на скаляр
$$
\lambda \cdot \vec{a} \in \mathbb{R}^{\vec{a}}
$$


In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5], dtype=float)

print(a)  # [1. 2. 3. 4. 5.]

b = 5*a

print(b)  # [ 5. 10. 15. 20. 25.]


[1. 2. 3. 4. 5.]
[ 5. 10. 15. 20. 25.]


## Додавання та віднімання двох векторів

Дана операція можлива лише у тому випадку, якщо наші вектори однієї розмірності — тобто у них однакова к-сть елементів.

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5], dtype=float)
print(a.size)  # 5

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)  # [5 7 9]
print(a - b)  # [-3 -3 -3]

5
[5 7 9]
[-3 -3 -3]
