<a href="https://colab.research.google.com/github/SiracencoSerghei/DataScienceHW/blob/main/example_kaggle/les_8/les_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)

2.18.0


Variable та Tensor(constant)

In [2]:
b = tf.constant([4, 5, 6])

In [7]:
c = tf.Variable([1, 2, 3])

In [3]:
type(b)

tensorflow.python.framework.ops.EagerTensor

In [8]:
type(c)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [9]:
c.assign([1, 1, 1])

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([1, 1, 1], dtype=int32)>

In [31]:
a = tf.Variable([[4,5,6],
                 [4,5,6],
                 [4,5,6],
                 [4,5,6]], name='speed')


In [32]:
a.shape

TensorShape([4, 3])

In [25]:
tf.reshape(a, (3, 4))

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[5, 6, 7, 5],
       [6, 7, 5, 6],
       [7, 5, 6, 7]], dtype=int32)>

In [23]:
tf.size(a).numpy()

12

In [35]:
# a.assign_add([1,1,1])

delta = tf.ones((4,3), dtype=a.dtype)  # Міняємо на a.dtype

a.assign_add(delta)  # Додаємо значення
print(a.numpy())  # Виводимо результат

a.assign_add(delta)

[[7 8 9]
 [7 8 9]
 [7 8 9]
 [7 8 9]]


<tf.Variable 'UnreadVariable' shape=(4, 3) dtype=int32, numpy=
array([[ 8,  9, 10],
       [ 8,  9, 10],
       [ 8,  9, 10],
       [ 8,  9, 10]], dtype=int32)>

In [36]:
b = tf.constant([[5.],[5.], [5.], [5.] ])

In [37]:
b

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[5.],
       [5.],
       [5.],
       [5.]], dtype=float32)>

In [39]:
s = tf.reshape(b, (2,2))

In [40]:
s.numpy()

array([[5., 5.],
       [5., 5.]], dtype=float32)

In [41]:
import numpy as np

x_array = np.array([1,2,3])
x_tensor = tf.convert_to_tensor(x_array)

In [42]:
x_tensor/3

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.33333333, 0.66666667, 1.        ])>

In [46]:
tensor = tf.constant(x_array)
zeros = tf.zeros((4, 5))

In [47]:
zeros

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [50]:
ones = tf.ones(zeros.shape)

In [51]:
ones

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [45]:
tensor

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

---
# Поелементне попарне множення
---

In [52]:
b = tf.Variable([[1, 2],
                 [1, 2]])

c = tf.Variable([[1, 2],
                 [3, 4]])

print(b*c)

tf.Tensor(
[[1 4]
 [3 8]], shape=(2, 2), dtype=int32)


---
# Обчислювальний граф
---

In [68]:
import time

# Оригінальна функція без графа
def formula(x, y, b):
    x = tf.matmul(x, y)
    x = x + b
    return x

# Перетворена функція з графом
func_that_uses_a_graph = tf.function(formula)

# Тестові дані
x1 = tf.constant([[1., 2.]])
y1 = tf.constant([[2.], [3.]])
b1 = tf.constant(4.)

# Замір часу для оригінальної функції
start_time = time.time()
orig_value = formula(x1, y1, b1).numpy()
orig_time = time.time() - start_time

# Замір часу для функції з графом
start_time = time.time()
graph_value = func_that_uses_a_graph(x1, y1, b1).numpy()
graph_time = time.time() - start_time

# Виведення результатів
print(f"Original function result: {orig_value}, Time: {orig_time:.6f} seconds")
print(f"Graph function result: {graph_value}, Time: {graph_time:.6f} seconds")

# Перевірка рівності результатів
print(f"Are the results the same? {orig_value == graph_value}")


Original function result: [[12.]], Time: 0.001401 seconds
Graph function result: [[12.]], Time: 0.015527 seconds
Are the results the same? [[ True]]


In [56]:
x1.shape

TensorShape([1, 2])

In [66]:
y1.shape

TensorShape([2, 1])

In [67]:
# decoration

@tf.function
def function_that_uses_a_graph(x, y, b):
    x = tf.matmul(x, y)
    x = x + b
    return x

# Тестові дані
x1 = tf.constant([[1., 2.]])
y1 = tf.constant([[2.], [3.]])
b1 = tf.constant(4.)

# Замір часу для оригінальної функції
start_time = time.time()
orig_value = formula(x1, y1, b1).numpy()
orig_time = time.time() - start_time

# Замір часу для функції з графом
start_time = time.time()
graph_value = function_that_uses_a_graph(x1, y1, b1).numpy()
graph_time = time.time() - start_time

# Виведення результатів
print(f"Original function result: {orig_value}, Time: {orig_time:.6f} seconds")
print(f"Graph function result: {graph_value}, Time: {graph_time:.6f} seconds")

# Перевірка рівності результатів
print(f"Are the results the same? {orig_value == graph_value}")


Original function result: [[12.]], Time: 0.001943 seconds
Graph function result: [[12.]], Time: 0.060230 seconds
Are the results the same? [[ True]]


Для маленьких обчислень різниця в часі може бути незначною, але для великих обсягів даних або численних викликів граф обчислень дасть значні переваги в продуктивності.

Початковий час для графа може бути більшим через процес компіляції, але він стає набагато швидшим при повторних викликах.

In [82]:
# Оголошення ReLU активації

#  @tf.function
# def relu_activation(x):
#   print(type(x))
#   if tf.greater(x, 0):
#     return x1
#   return 0

@tf.function
def relu_activation(x):
    x = tf.cast(x, tf.float32)  # Приводимо вхід до float32
    if tf.greater(x, 0):
        return x  # Повертаємо x як float32
    return tf.constant(0.0, dtype=tf.float32)  # Повертаємо 0.0 як float32

q=tf.constant(1)
z = tf.constant(-1)
print(relu_activation(q).numpy())
print(relu_activation(z).numpy())

1.0
0.0


---
# Автоматичне диференціювання
---

In [84]:
def f(x):
  return 1/x**2

x = tf.Variable(1.0)
with tf.GradientTape() as tape:
  y = f(x)
  dy_dx = tape.gradient(y, x)
  print(dy_dx)

tf.Tensor(-2.0, shape=(), dtype=float32)


---
# Створення нейронної мережи
---

## Linear regression, one parameter(argument)

In [85]:
class SimpleModule(tf.Module):
  def __init__(self, name=None):
    super().__init__(name=name)
    self.w = tf.Variable(5.0)
    self.b = tf.Variable(5.0)

  def __call__(self, x):
    return self.w * x + self.b

simple_module = SimpleModule(name="simple")

simple_module(tf.constant([5.0, 3.0])).numpy()

array([30., 20.], dtype=float32)

In [98]:
class DenseLayer(tf.Module):
  def __init__(self, in_features, out_features, name=None):
    super().__init__(name=name)
    self.w = tf.Variable(
      tf.random.normal([in_features, out_features]), name='Weights')
    self.b = tf.Variable(tf.zeros([out_features]), name='Bias')

  def __call__(self, x):
    y = tf.matmul(x, self.w) + self.b
    return tf.nn.relu(y)

class NN(tf.Module):
  def __init__(self, name=None):
    super().__init__(name=name)
    self.layer_2 = DenseLayer(in_features=3, out_features=3)
    self.layer_3 = DenseLayer(in_features=3, out_features=1)
  def __call__(self, x):
    x = self.layer_2(x)
    return self.layer_3(x)

model = NN(name="neural_network")
print("results: ", model(tf.constant([[2.0, 2.0, 2.0]])))

results:  tf.Tensor([[0.30532917]], shape=(1, 1), dtype=float32)


---
# Навчання нейронної мережи
---

In [99]:
class LinearModel(tf.Module):
  def __init__(self, **kwargs):
    super().__init__(**kwargs)
    self.w = tf.Variable(5.0)
    self.b = tf.Variable(0.0)

  def __call__(self, x):
    return self.w * x + self.b

In [100]:
def loss(target_y, predicted_y):
  return tf.reduce_mean(tf.square(target_y - predicted_y))

def train(model, x, y, learning_rate):
  with tf.GradientTape() as t:
    current_loss = loss(y, model(x))
    dw, db = t.gradient(current_loss, [model.w, model.b])
    model.w.assign_sub(learning_rate * dw)
    model.b.assign_sub(learning_rate * db)

In [102]:
def training_loop(model, x, y):
  for epoch in range(20):
    train(model, x, y, learning_rate=0.1)
    current_loss = loss(y, model(x))
    print(f"Epoch {epoch:2d}: W={model.w.numpy():1.2f} b={model.b.numpy():1.2f}, loss={current_loss:2.5f}")


---
# Штучні тестові дані
---

$$
y = 3x + 2 + \text{noise}
$$


In [103]:
TRUE_W = 3.0
TRUE_B = 2.0

NUM_EXAMPLES = 1000

x = tf.random.normal(shape=[NUM_EXAMPLES])
noise = tf.random.normal(shape=[NUM_EXAMPLES])
y = x * TRUE_W + TRUE_B + noise

In [104]:
linear_model = LinearModel()
training_loop(linear_model, x, y)

Epoch  0: W=4.60 b=0.40, loss=6.09588
Epoch  1: W=4.27 b=0.72, loss=4.23869
Epoch  2: W=4.01 b=0.97, loss=3.05209
Epoch  3: W=3.81 b=1.18, loss=2.29394
Epoch  4: W=3.64 b=1.34, loss=1.80953
Epoch  5: W=3.51 b=1.47, loss=1.50003
Epoch  6: W=3.40 b=1.57, loss=1.30228
Epoch  7: W=3.32 b=1.65, loss=1.17593
Epoch  8: W=3.25 b=1.72, loss=1.09520
Epoch  9: W=3.19 b=1.77, loss=1.04361
Epoch 10: W=3.15 b=1.82, loss=1.01065
Epoch 11: W=3.12 b=1.85, loss=0.98960
Epoch 12: W=3.09 b=1.88, loss=0.97614
Epoch 13: W=3.07 b=1.90, loss=0.96754
Epoch 14: W=3.05 b=1.91, loss=0.96205
Epoch 15: W=3.03 b=1.93, loss=0.95854
Epoch 16: W=3.02 b=1.94, loss=0.95629
Epoch 17: W=3.01 b=1.95, loss=0.95486
Epoch 18: W=3.01 b=1.95, loss=0.95395
Epoch 19: W=3.00 b=1.96, loss=0.95336


In [105]:
linear_model.w

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.9997596740722656>

In [106]:
linear_model.b

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.9599982500076294>